"""
Fill in this information and save this file as Secret_Config.py
to be able to run the application.

"""

PGDATABASE = "ENTER THE NAME OF THE DATABASE"
PGUSER = "ENTER THE DATABASE USER"
PGPASSWORD = "ENTER THE PASSWORD"
PGHOST = "ENTER THE DNS ADDRESS OR IP ADDRESS OF THE SERVER"
PGPORT = 5432 # DEFAULT IS 5432, BUT IT MAY CHANGE IN YOUR DB